# Generated by Django 4.1.2 on 2022-11-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('log', models.TextField()),
                ('pipeline_path', models.CharField(max_length=255)),
                ('pipeline_config', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('template_path', models.CharField(max_length=255)),
                ('template_config', models.CharField(max_length=255)),
            ],
        ),
    ]
