# Generated by Django 4.1.2 on 2022-11-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextflowRedemption', '0002_pipeline_pipleline_parameters_alter_pipeline_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_config',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_config',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
