# Generated by Django 4.1.2 on 2022-11-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextflowRedemption', '0003_alter_pipeline_pipeline_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_config',
            field=models.CharField(default='', max_length=255),
        ),
    ]
