# Generated by Django 4.1.2 on 2022-11-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextflowRedemption', '0004_pipeline_location_alter_template_template_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_config',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
