# Generated by Django 4.1.2 on 2022-11-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NextflowRedemption', '0006_added_parameter_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='pipeline',
        ),
    ]
