# Generated by Django 4.1.2 on 2022-11-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NextflowRedemption', '0007_remove_parameter_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
